apiVersion: v2
name: ftl
description: |
  A Helm chart for Kubernetes that deploys FTL
home: https://github.com/block/ftl
version: 0.412.2
appVersion: 0.412.2
dependencies:
  - name: postgresql
    version: 15.5.38
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
